# States
RESET=$(tput sgr0)
BOLD=$(tput bold)

# General
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
LGREEN=$(tput setaf 2)
ORANGE=$(tput setaf 3)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)

# Status messages
PASS="${BOLD}${GREEN}[ PASSED! ]${RESET}"
FAIL="${BOLD}${RED}[ FAILED! ]${RESET}"
WARN="${BOLD}${YELLOW}[ WARNING! ]${RESET}"

# Headings
head() {
    echo "${BOLD}${MAGENTA}==> $1${RESET}"
}

# Processes
proc() {
    echo "${ORANGE}=> $1${RESET}"
}

# Prompts
prom() {
    echo -n "${CYAN}> $1${RESET} "
}

# Normal text
text() {
    echo "${GREEN}$1${RESET}"
}
